### ISSUE TITLE
As a user I want to recover my password on trashradar

### ISSUE THREAD

**Issue by marton987** [spry-group/trashradar-api#18]
**Acceptance criteria**
1. Given an user posts a json object to `/account/recover_password/` 
      1.  When the user is authenticated.
             1. Then there will be an HTTP response with status 200 OK.
             2. The response will contains a JSON object with the user details
             4. The user is authenticated

   2.  When the user is unauthenticated.
             1. Then there will be an HTTP response with status 200 OK.
             2. The response will contains a JSON object with the user details
             3. The user will receive an email with the verification code
             4. The user is unauthenticated

**Comment by carlosabbate** [comment]
Closed by https://github.com/spry-group/trashradar/pull/30.
