### ISSUE TITLE
As a user I want upload picture of a place with trash

### ISSUE THREAD

**Issue by marton987** [spry-group/trashradar-api#20]
**Acceptance criteria**
1. Given an user posts a json object to `/complaint/` 
      1.  When the user is authenticated.
             1. Then there will be an HTTP response with status 202 OK.
             2. Then a complaint object is updated 
             3. Then a complaint object will have pictures associated

   2.  When the user is unauthenticated.
             1. Then there will be an HTTP response with status 403 Forbidden

**Comment by carlosabbate** [comment]
Closed by https://github.com/spry-group/trashradar-api/pull/66.
