### ISSUE TITLE
As a user I like to view all places with trash 

### ISSUE THREAD

**Issue by marton987** [spry-group/trashradar-api#22]
**Acceptance criteria**
1. Given an user get to `/complaint/` 
      1.  When the client is authenticated.
             1. Then there will be an HTTP response with status 200 OK.
             2. Then receive a list with all the complaints on a specific location

   2.  When the user is unauthenticated.
             1. Then there will be an HTTP response with status 200 OK.
             2. Then receive a list with all the complaints on a specific location

**Comment by carlosabbate** [comment]
Closed by https://github.com/spry-group/trashradar-api/pull/66.
