### ISSUE TITLE
Do not import assets directly on the HTML

### ISSUE THREAD

**Issue by carlosabbate** [spry-group/trashradar-api#47]
Related to https://github.com/spry-group/trashradar-api/issues/46.

We should not be importing CSS (https://github.com/spry-group/trashradar/blob/625623f637eb110d3e4dd0452658104827489039/tr-site/src/index.html#L9) or JS (https://github.com/spry-group/trashradar/blob/625623f637eb110d3e4dd0452658104827489039/tr-site/src/index.html#L15) in hte HTML.

We should be using https://ng-bootstrap.github.io for bootstrap.

**Comment by Klemensas** [comment]
Solved by https://github.com/spry-group/trashradar/pull/21
